//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truck_Assignment_And_Monitoring.Admin
{


    public partial class NewDriver
    {
        protected global::System.Web.UI.WebControls.TextBox FirstName;
        protected global::System.Web.UI.WebControls.TextBox MiddleName;
        protected global::System.Web.UI.WebControls.TextBox LastName;
        protected global::System.Web.UI.WebControls.TextBox Mobile;
        protected global::System.Web.UI.WebControls.TextBox Phone;
        protected global::System.Web.UI.WebControls.TextBox Email;
        protected global::System.Web.UI.WebControls.TextBox Address;
        protected global::System.Web.UI.WebControls.TextBox Login;
        protected global::System.Web.UI.WebControls.TextBox Password;
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;
    }
}
