//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truck_Assignment_And_Monitoring.Cargo
{


    public partial class NewCargo
    {
        protected global::System.Web.UI.WebControls.TextBox Details;
        protected global::System.Web.UI.WebControls.TextBox PickUpPlace;
        protected global::System.Web.UI.WebControls.TextBox Destination;
        protected global::System.Web.UI.WebControls.TextBox Quantity;
        protected global::System.Web.UI.WebControls.DropDownList CargoType;
    }
}
