//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truck_Assignment_And_Monitoring.Driver
{


    public partial class NegotiateValues
    {
        protected global::System.Web.UI.WebControls.Label TruckID;
        protected global::System.Web.UI.WebControls.Label CargoID;
        protected global::System.Web.UI.WebControls.Label pickerdate;
        protected global::System.Web.UI.WebControls.Label dropperdate;
        protected global::System.Web.UI.WebControls.TextBox Rate;
        protected global::System.Web.UI.WebControls.DropDownList CargoType;
    }
}
